# Open quality menu with 'F' or 'f'
F script-binding quality_menu/video_formats_toggle
f script-binding quality_menu/video_formats_toggle

# Open audio quality menu with 'Alt+f'
Alt+f script-binding quality_menu/audio_formats_toggle
