# Use yt-dlp for streaming and web links (ff2mpv)
script-opts-append=ytdl_hook-ytdl_path=yt-dlp

# Preferred default stream quality (e.g., max 1080p, 60fps)
#ytdl-format=bestvideo[height<=?1080][fps<=?60]+bestaudio/best

# Disable the native, ugly stock controller layout
osc=no

# Disable the default blocky progress bar
#osd-bar=no

# Disable native borders so uosc can draw clean Wayland windows
#border=no

# Optional: Removes the native OS window title bar for a cleaner look
#title-bar=no

watch-later-options-remove=sub-pos
watch-later-options-remove=osd-margin-y

# Network/IPTV specific performance
demuxer-max-bytes=450MiB        # Allocates a solid memory buffer for network streams
demuxer-max-back-bytes=150MiB    # Limits memory wasted on seeking backward in a live stream
force-window=yes                # Keeps the player window open even if a channel takes a second to load

# Enable hardware decoding
hwdec=vaapi

# Since you are running gpu-next with a Wayland/Vulkan context (waylandvk):
gpu-api=vulkan
vo=gpu-next
