-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(b4a267)",
			inactive_border = "rgb(898371)",
		},
	},
	group = {
		col = {
			border_active = "rgb(b4a267)",
			border_inactive = "rgb(898371)",
			border_locked_active = "rgb(ff7b6e)",
			border_locked_inactive = "rgb(898371)",
		},
		groupbar = {
			col = {
				active = "rgb(b4a267)",
				inactive = "rgb(898371)",
				locked_active = "rgb(ff7b6e)",
				locked_inactive = "rgb(898371)",
			},
		},
	},
})
