-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Breeze_Hacked")
hl.env("XCURSOR_THEME", "Breeze_Hacked")
hl.env("HYPRCURSOR_SIZE", "28")
hl.env("XCURSOR_SIZE", "28")

hl.config({
	cursor = {
		hide_on_key_press = true,
		inactive_timeout = 5,
	},
})
