-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("HYPRCURSOR_SIZE", "20")
hl.env("XCURSOR_SIZE", "20")

hl.config({
	cursor = {
		hide_on_key_press = true,
		inactive_timeout = 4,
	},
})
