-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 1,
		resize_on_border = true,
		layout = "master",
	},
	master = {
		orientation = "left",
		new_status = "slave",
		new_on_top = false,
		mfact = 0.5,
	},
	decoration = {
		rounding = 14,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
